.TH "SEKI" 1 "15 Jan 2017" "seki 0.1.4" "User Commands"

.SH NAME
.PP
seki \- your own personal Suiseiseki.

.SH SYNOPSIS
.PP
\fBseki\fR [\fIoption\fR] [\fIfiller\fR]

.SH DESCRIPTION
.PP
This program is just a parody of Suiseiseki manner of speech.

.SH OPTIONS
.PP
\fIseki\fR accept the following options:
.TP
\fB-h\fR Print helpful message and exit.
.TP
\fB-v\fR Print version and exit.
.TP
\fB--\fR Stop parsing options and treat the next argument (if present) as filler.

.SH AUTHOR
.PP
Written by Ivan Sokolov.

.SH REPORTING BUGS
.PP
seki's bugtracker is located at the following address: <https://github.com/sirikid/seki/issues>

.SH COPYRIGHT
.PP
Copyright (c) 2015-2017 Ivan Sokolov, WTFPL.

.SH SEE ALSO
.PP
\fIyes(1)\fR
